export default [
  {
    name: "Bike Retro Basket",
    img: "b1",
    description: "Bike RetroStyle Basket and Light for good old days",
    price: 29.99,
    id: 1,
    keywords: {
      b: true,
      bb: true,
    },
  },
  {
    name: "Watermelon Bike Wheels",
    img: "b2",
    description: "As the title says. Watermelon wheels",
    price: 199.95,
    id: 2,
    keywords: {
      b: true,
      x: true,
    },
  },
  {
    name: "Bike Paintjob",
    img: "b3",
    description: "Whatever this is IDK",
    price: 174.99,
    id: 3,
    keywords: {
      b: true,
      bb: true,
      pj: true,
    },
  },
  {
    name: "Bike Basic Helmet",
    img: "bh1",
    description: "A helmet for bikers. Comes in many colors",
    price: 34.99,
    id: 4,
    keywords: {
      b: true,
      bb: true,
      bh: true,
    },
  },
  {
    name: "Car Paintjob  Light-Blue",
    img: "c1",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 499.99,
    id: 5,
    keywords: {
      c: true,
      pj: true,
    },
  },
  {
    name: "Car Paintjob Black",
    img: "c2",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 449.95,
    id: 6,
    keywords: {
      c: true,
      pj: true,
    },
  },
  {
    name: "Red Audi",
    img: "c3",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 39999.99,
    id: 7,
    keywords: {
      c: true,
      pj: true,
    },
  },
  {
    name: "Metallic Paintjob",
    img: "c4",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 4999.95,
    id: 8,
    keywords: {
      c: true,
      pj: true,
      x: true,
    },
  },
  {
    name: "Pink Paintjob",
    img: "c5",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 999.95,
    id: 9,
    keywords: {
      c: true,
      pj: true,
    },
  },
  {
    name: "Car Interior Retro",
    img: "ci1",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 3299.95,
    id: 10,
    keywords: {
      ci: true,
      x: true,
    },
  },
  {
    name: "Modern Car Interior",
    img: "ci2",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 5099.99,
    id: 11,
    keywords: {
      ci: true,
      x: true,
    },
  },
  {
    name: "Motrobike black/silver",
    img: "mb1",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 25500,
    id: 12,
    keywords: {
      mb: true,
      pj: true,
    },
  },
  {
    name: "Motrobike Retro-style",
    img: "mb2",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 14559.95,
    id: 13,
    keywords: {
      mb: true,
      pj: true,
    },
  },
  {
    name: "Motorbike Helmet Black",
    img: "mbh1",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 499.95,
    id: 14,
    keywords: {
      mb: true,
      mbh: true,
      mbg: true,
    },
  },
  {
    name: "Sport Motorbike Helmet",
    img: "mbh2",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 599.95,
    id: 15,
    keywords: {
      mb: true,
      mbh: true,
      mbg: true,
    },
  },
  {
    name: "Motorbike Helmet Red/Orange",
    img: "mbh3",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 459.99,
    id: 16,
    keywords: {
      mb: true,
      mbh: true,
      mbg: true,
      pj: true,
    },
  },
  {
    name: "Vinyl / Paintjob mix 1",
    img: "v1",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 2500,
    id: 17,
    keywords: {
      c: true,
      v: true,
      pj: true,
    },
  },
  {
    name: "Vinyl / Paintjob Pepsi Zero",
    img: "v2",
    description: "aksjda sdiahsdohas diahsid asiuh as",
    price: 2500,
    id: 18,
    keywords: {
        c: true,
        v: true,
        pj: true,
      },
  },
];
